name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  security:
    name: Prisma Cloud CAS scan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        env:
          PRISMA_API_URL: ${{ secrets.PRISMA_API_URL }}
        with:
          api-key: ${{ secrets.BC_API_KEY }}
          use_enforcement_rules: true
          quiet: true
